
### quality-zsh/.github/workflows/quality-reusable.yml
```yaml
name: quality-reusable
on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Format
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: cargo test --workspace --all-features --verbose

      - name: Install tools
        run: |
          cargo install cargo-llvm-cov
          cargo install cargo-deny
          cargo install cargo-audit

      - name: Cargo deny
        run: cargo deny check -q

      - name: Cargo audit
        run: cargo audit -q

      - name: Coverage (fail if <80%)
        run: cargo llvm-cov --workspace --fail-under-lines 80 --lcov --output-path lcov.info

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-lcov
          path: lcov.info
